services:
  - type: web
    name: express
    env: node
    repo: https://github.com/bencgreenberg/synthetics-workshop-web-app.git
    scaling:
      minInstances: 1
      maxInstances: 2
      targetMemoryPercent: 60
    buildCommand: npm install
    startCommand: npm start

envVarGroups:
  - name: user-settings
    envVars:
      - key: NEW_RELIC_LICENSE_KEY
        sync: false
